Rolling window cross-evaluation
dataiku/dss-plugin-timeseries-forecast pull request #68
Opened 2021-11-18 19:11 UTC by StanislasGuinel

2021-11-20 16:40 UTC, alexcombessie commented
Nice

2021-11-29 15:17 UTC, Marsobad requested changes
Nice job for the new cross validation feature!
# Logic errors
I haven't spotted any significant logic errors. You might want to add a minI + maxI for the number of windows and the cutoff period in the UI.

# Readability
At first sight, I found it hard to deal with the names of some attributes or methods such as `rolling_windows_cut_lengths_train_test_pairs` and `rolling_windows_unique_cut_lengths`. Yet, once I understood what they meant, I could see clearly through your code. These names are so specific that they don't foster any confusion. So, once you get them, you can't get it wrong. I don't have any better naming ideas anyway. 

# Make the code shorter
Some default values are set twice, cf review comments

# Test coverage
LGTM, we could also test the results of `_reorder_metrics_df` 

# Usage
You chose a different implementation from sklearn, so some data scientists might be curious about your references.  That's why, it would be nice to add a link to a paper on cross validation in the settings of the recipe and in the doc of the plugin.

2021-12-02 11:33 UTC, StanislasGuinel commented on custom-recipes/timeseries-forecast-1-train-evaluate/recipe.json
> +            "defaultValue": 1,
Nope I just missed it, done in f30fae1

2021-12-02 11:35 UTC, StanislasGuinel commented on python-lib/dku_io_utils/model_selection.py
> +            # important for compatibility with models trained before the implementation of the cross-validation
It was actually removed because we don't show aggregation across rolling windows anymore

2021-12-02 11:36 UTC, StanislasGuinel commented on python-lib/dku_io_utils/config_handler.py
> +                {"type": "not_in", "op": [0]},
This operator doesn't exist in dkulib, I don't know if we want to add it to the dkulib repo because it's just a subcase of not_in

2021-12-02 11:37 UTC, StanislasGuinel commented on python-lib/gluonts_forecasts/model.py
> +        metrics = self._format_metrics(agg_metrics, item_metrics, train_list_dataset)
it's a small refactoring because `identifiers_columns` was actually not used in the training session

2021-12-02 11:38 UTC, StanislasGuinel commented on tests/python/unit/test_cross_validation.py
> +        assert set(rolling_windows_metrics[METRICS_DATASET.ROLLING_WINDOWS].unique()) == set((0, 1, 2))
Indeed np.array_equal is better, done in f30fae1

2021-12-02 11:38 UTC, StanislasGuinel commented on python-lib/gluonts_forecasts/gluon_dataset.py
> +            raise ValueError(
In d60d035, I made the error message more explicit by explaining where the min value comes from (minimum size to be able to train + some values are removed to make the train set in the evaluation process), but the DkuGluonDataset object is independent from the rolling windows indexes creation so it doesn't have access to the nb of windows and cutoff period params (it only knows where to cut the time series).
Actually, the figure returned by the error message is the right one = min_length to be able to train + maximum number of values that will be removed to create the first train dataset of the cross-validation process.
Example:
If prediction_length = 10, min_length = 20, cut_lengths = [30, 20, 10] and a timeseries of only 40 values, then the error is raised with the first cut_length of 30 with the message "Time series must have at least 50 (20+30) values."

2021-12-02 11:49 UTC, StanislasGuinel commented on python-lib/gluonts_forecasts/training_session.py
> +        self.rolling_windows_cut_lengths_train_test_pairs = self._compute_rolling_windows_cut_lengths_train_test_pairs()
Good catch, done in 5633012

2021-12-02 11:49 UTC, StanislasGuinel commented on python-lib/gluonts_forecasts/training_session.py
> +        No cross-validation is equivalent to 1 rolling window with a cut length of prediction_length for the train set and 0 for the test set.
Actually the same formula covers both cases (formula with rolling_windows_number=1 gives exactly [(self.prediction_length, 0)]).
The reason I made both the if statement and the comment was to make the distinction more explicit, obviously it was not clear, so I kept the comment and remove the if statement in 757c708

2021-12-02 11:53 UTC, StanislasGuinel commented on python-lib/gluonts_forecasts/training_session.py
> +        item_metrics, forecasts_df = model.train_evaluate(
Done in d642cce

2021-12-02 12:12 UTC, StanislasGuinel commented on python-lib/gluonts_forecasts/training_session.py
> +        self.rolling_windows_number = rolling_windows_number if timeseries_cross_validation else 1
I agree from a plugin usage perspective, but if we consider the lib independent, then it's a good practice to override the rolling_windows_number param with 1 if timeseries_cross_validation is False (to not have multiple windows and timeseries_cross_validation = False)

2021-12-02 12:19 UTC, StanislasGuinel commented on python-lib/gluonts_forecasts/training_session.py
> +    def train_evaluate(self, retrain=False):
good point, done in 5b0b35e

2021-12-02 12:19 UTC, StanislasGuinel commented on python-lib/gluonts_forecasts/training_session.py
> +        last_window = rolling_window_index == len(self.rolling_windows_cut_lengths_train_test_pairs) - 1
good catch, done in c1f1a2f

2021-12-02 12:23 UTC, StanislasGuinel commented on python-lib/gluonts_forecasts/training_session.py
> +                (self.prediction_length + (i - 1) * self.cutoff_period, (i - 1) * self.cutoff_period)
Yes I will explain how sliding windows are computed in the wordpress documentation (there is no a single source for that, it's more general knowledge about time series cross-validation).

2021-12-07 18:02 UTC, Marsobad commented on python-lib/dku_io_utils/config_handler.py
> +                {"type": "not_in", "op": [0]},
ok, nevermind

2021-12-07 18:02 UTC, Marsobad commented on python-lib/gluonts_forecasts/training_session.py
> +        self.rolling_windows_number = rolling_windows_number if timeseries_cross_validation else 1
true that

2021-12-07 18:14 UTC, Marsobad commented on python-lib/gluonts_forecasts/training_session.py
> +        No cross-validation is equivalent to 1 rolling window with a cut length of prediction_length for the train set and 0 for the test set.
oh ok !! I had understood "aucune cross validation n'est l'équivalent d'une rolling window..."

2021-12-07 18:20 UTC, Marsobad approved these changes
Great job!

2021-12-07 18:22 UTC, merged